'use strict';

const nconf = require.main.require('nconf');
const winston = require.main.require('winston');
const routeHelpers = require.main.require('./src/routes/helpers');

const plugin = {};

const CONFIG = {
  cid: 6,
  pageSize: 12,
  maxPageSize: 30,
  imageMax: 4,
  publicItemTtl: 72 * 60 * 60 * 1000,
  firstPageTtl: 2 * 60 * 1000,
  oldPageTtl: 72 * 60 * 60 * 1000,
  countsTtl: 45 * 1000,
  viewerTtl: 2 * 60 * 1000
};

const RE = {
  tiktokGlobal: /https?:\/\/(?:www\.)?tiktok\.com\/@[^/\s<>'"]+\/video\/(\d+)(?:\?[^\s<>'"]*)?/ig,
  tiktokOne: /https?:\/\/(?:www\.)?tiktok\.com\/@([^/\s<>'"]+)\/video\/(\d+)/i,
  tiktokShort: /https?:\/\/(?:vt|vm)\.tiktok\.com\/[^\s<>'"]+/ig,
  tiktokShortOne: /https?:\/\/(?:vt|vm)\.tiktok\.com\/[^\s<>'"]+/i,
  tiktokToken: /(?:https?[-:\/]+)?(?:www[.-])?tiktok[.-]com[-\/\w@.%=&?]+/ig,
  imageExt: /\.(png|jpe?g|gif|webp|avif)(?:[?#].*)?$/i,
  audioExt: /\.(m4a|mp3|wav|ogg|oga|webm|aac)(?:[?#].*)?$/i
};

let db;
let Topics;
let Posts;
let User;
let Privileges;
let routeReady = false;
const cache = new Map();

function now() { return Date.now(); }
function norm(value) { return String(value || '').replace(/\s+/g, ' ').trim(); }
function safeNumber(value, fallback = 0) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
}
function getCached(key) {
  const record = cache.get(key);
  if (!record || record.expiresAt <= now()) {
    cache.delete(key);
    return null;
  }
  return record.value;
}
function setCached(key, value, ttl) {
  cache.set(key, { value, expiresAt: now() + ttl });
  return value;
}
function deleteCachePrefix(prefix) {
  for (const key of cache.keys()) {
    if (key.startsWith(prefix)) cache.delete(key);
  }
}
function invalidateFeedCaches() {
  deleteCachePrefix('feed:');
  deleteCachePrefix('item:');
  deleteCachePrefix('counts:');
  deleteCachePrefix('viewer:');
}
async function getModule(path) {
  return require.main.require(path);
}
async function ensureModules() {
  db = db || await getModule('./src/database');
  Topics = Topics || await getModule('./src/topics');
  Posts = Posts || await getModule('./src/posts');
  User = User || await getModule('./src/user');
  Privileges = Privileges || await getModule('./src/privileges');
}
function getReqUid(req) {
  return Number((req && (req.uid || (req.user && req.user.uid) || (req.session && req.session.uid))) || 0);
}
function canonicalTikTokUrl(url) {
  const text = String(url || '').replace(/&amp;/g, '&').trim();
  const match = text.match(RE.tiktokOne);
  return match ? `https://www.tiktok.com/@${match[1]}/video/${match[2]}` : text;
}
function collectTikToks(text) {
  const seen = new Set();
  const out = [];
  String(text || '').replace(RE.tiktokGlobal, (match, videoId) => {
    if (videoId && !seen.has(videoId)) {
      seen.add(videoId);
      out.push({ videoId, url: canonicalTikTokUrl(match) });
    }
    return match;
  });
  return out;
}
async function resolveTikTokShortUrl(url) {
  const raw = String(url || '').replace(/&amp;/g, '&').trim();
  if (!raw || !RE.tiktokShortOne.test(raw)) return '';
  const key = `short:${raw}`;
  const cached = getCached(key);
  if (cached !== null) return cached;
  try {
    if (typeof fetch !== 'function') return setCached(key, '', 6 * 60 * 60 * 1000);
    const res = await fetch(raw, { method: 'GET', redirect: 'follow' });
    const finalUrl = res && res.url ? res.url : '';
    const match = finalUrl.match(RE.tiktokOne);
    if (match && match[2]) return setCached(key, canonicalTikTokUrl(finalUrl), CONFIG.publicItemTtl);
  } catch (err) {
    winston.warn(`[nodebb-plugin-peipe-video] TikTok short URL resolve failed: ${raw} ${err.message}`);
  }
  return setCached(key, '', 6 * 60 * 60 * 1000);
}
async function collectTikToksAsync(text) {
  const out = collectTikToks(text);
  const seen = new Set(out.map(item => item.videoId));
  const shorts = [];
  String(text || '').replace(RE.tiktokShort, (match) => {
    if (!shorts.includes(match)) shorts.push(match);
    return match;
  });
  for (const shortUrl of shorts.slice(0, 4)) {
    const resolved = await resolveTikTokShortUrl(shortUrl);
    const match = resolved && resolved.match(RE.tiktokOne);
    if (match && match[2] && !seen.has(match[2])) {
      seen.add(match[2]);
      out.push({ videoId: match[2], url: canonicalTikTokUrl(resolved) });
    }
  }
  return out;
}
function isAutoGeneratedText(text) {
  const clean = norm(String(text || '').replace(/\u00a0/g, ' ').replace(/[•・·|｜_／/\\-]+/g, ' ').replace(/[：]/g, ':'));
  if (!clean) return true;
  if (/^https?:\/\/(?:vt|vm|www\.)?tiktok\./i.test(clean)) return true;
  return /^(?:动态|新动态|图片分享|图片动态|语音消息|语音动态|voice message|audio message|image|photo|picture)(?:\s*:?\s*\d{1,2}:\d{2}(?::\d{2})?)?$/i.test(clean);
}
function cleanDisplayText(text) {
  const raw = String(text || '')
    .replace(RE.tiktokGlobal, '')
    .replace(RE.tiktokShort, '')
    .replace(RE.tiktokToken, '')
    .replace(/!\[[^\]]*\]\([^)]+\)/g, '')
    .replace(/\[\s*(?:语音消息|语音动态|voice\s*message|audio\s*message)[^\]]*\]\([^)]+\)/ig, '')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&');
  return raw.split(/[\r\n]+/)
    .map(norm)
    .filter(line => line && !isAutoGeneratedText(line))
    .join('\n');
}
function parseDurationFromUrl(url) {
  try {
    const u = new URL(String(url || ''), 'https://example.com');
    return Math.max(0, safeNumber(u.searchParams.get('haa8dur') || u.searchParams.get('dur') || u.searchParams.get('duration'), 0));
  } catch (err) {
    const m = String(url || '').match(/[?&](?:haa8dur|dur|duration)=(\d+)/i);
    return m ? safeNumber(m[1], 0) : 0;
  }
}
function parseMediaFromContent(content) {
  const raw = String(content || '');
  const out = { text: '', images: [], audios: [], tiktoks: collectTikToks(raw) };
  raw.replace(/<img[^>]+src=["']([^"']+)["'][^>]*>/ig, (m, src) => {
    if (src && !out.images.includes(src)) out.images.push(src);
    return m;
  });
  raw.replace(/<audio[^>]+src=["']([^"']+)["'][^>]*>/ig, (m, src) => {
    if (src && !out.audios.some(item => item.url === src)) out.audios.push({ url: src, label: '语音消息', duration: parseDurationFromUrl(src) });
    return m;
  });
  raw.replace(/<source[^>]+src=["']([^"']+)["'][^>]*>/ig, (m, src) => {
    if (src && RE.audioExt.test(src) && !out.audios.some(item => item.url === src)) out.audios.push({ url: src, label: '语音消息', duration: parseDurationFromUrl(src) });
    return m;
  });
  raw.replace(/!\[[^\]]*\]\(([^)]+)\)/g, (m, src) => {
    if (src && !out.images.includes(src)) out.images.push(src);
    return m;
  });
  raw.replace(/\[([^\]]*)\]\(([^)]+)\)/g, (m, label, href) => {
    if (href && RE.audioExt.test(href) && !out.audios.some(item => item.url === href)) {
      out.audios.push({ url: href, label: norm(label) || '语音消息', duration: parseDurationFromUrl(href) });
    } else if (href && RE.imageExt.test(href) && !out.images.includes(href)) {
      out.images.push(href);
    }
    return m;
  });
  out.text = cleanDisplayText(raw);
  out.images = out.images.slice(0, CONFIG.imageMax);
  return out;
}
async function parseMediaFromContentAsync(content) {
  const media = parseMediaFromContent(content);
  media.tiktoks = await collectTikToksAsync(content);
  return media;
}
function topicHref(topic) {
  const tid = topic && topic.tid;
  const slug = topic && topic.slug;
  if (!tid) return '#';
  return slug ? `/topic/${slug}` : `/topic/${tid}`;
}
async function getTids(cid, start, stop) {
  await ensureModules();
  let tids = [];
  if (db && typeof db.getSortedSetRevRange === 'function') {
    tids = await db.getSortedSetRevRange(`cid:${cid}:tids:create`, start, stop);
    if (!tids || !tids.length) tids = await db.getSortedSetRevRange(`cid:${cid}:tids`, start, stop);
  }
  return (tids || []).map(String).filter(Boolean);
}
async function getViewer(uid, item) {
  if (!uid || !item) return { liked: false, following: false, canComment: true, canManage: false };
  const key = `viewer:${uid}:${item.tid}:${item.pid || ''}`;
  const cached = getCached(key);
  if (cached) return cached;
  let liked = false;
  let following = false;
  let canManage = false;
  try {
    if (item.pid && Posts && typeof Posts.hasVoted === 'function') liked = !!(await Posts.hasVoted(item.pid, uid));
  } catch (err) {}
  try {
    if (item.author && item.author.uid && User && typeof User.isFollowing === 'function') following = !!(await User.isFollowing(uid, item.author.uid));
  } catch (err) {}
  try {
    canManage = await canManageItem(uid, item);
  } catch (err) {}
  return setCached(key, { liked, following, canComment: true, canManage }, CONFIG.viewerTtl);
}
async function canManageItem(uid, item) {
  await ensureModules();
  if (!uid || !item) return false;
  try {
    if (User && typeof User.isAdministrator === 'function' && await User.isAdministrator(uid)) return true;
    if (User && typeof User.isGlobalModerator === 'function' && await User.isGlobalModerator(uid)) return true;
    if (item.author && String(item.author.uid || '') === String(uid)) return true;
    if (Privileges && Privileges.categories && typeof Privileges.categories.isModerator === 'function') {
      const mod = await Privileges.categories.isModerator(item.cid || CONFIG.cid, uid);
      if (mod) return true;
    }
  } catch (err) {}
  return false;
}
async function buildPublicItem(tid, uid = 0) {
  await ensureModules();
  const key = `item:${tid}`;
  let item = getCached(key);
  if (!item) {
    const [topic, mainPost] = await Promise.all([
      Topics.getTopicData(tid),
      Topics.getMainPost ? Topics.getMainPost(tid, uid) : null
    ]);
    if (!topic || !topic.tid || Number(topic.deleted || 0)) return null;
    const post = mainPost || {};
    const content = post.content || post.raw || topic.content || topic.title || '';
    const media = await parseMediaFromContentAsync(content);
    if (!media.tiktoks.length && !media.images.length) return null;
    const authorUid = post.uid || topic.uid || 0;
    let author = { uid: authorUid, username: '用户', userslug: '', picture: '' };
    try {
      if (authorUid && User) author = await User.getUserFields(authorUid, ['uid', 'username', 'userslug', 'picture', 'status']);
    } catch (err) {}
    item = {
      tid: String(topic.tid),
      pid: String(post.pid || topic.mainPid || ''),
      cid: Number(topic.cid || CONFIG.cid),
      title: cleanDisplayText(topic.title || ''),
      text: media.text || cleanDisplayText(topic.title || ''),
      href: topicHref(topic),
      createdAt: Number(topic.timestamp || post.timestamp || 0),
      updatedAt: Number(topic.lastposttime || topic.timestamp || 0),
      author,
      images: media.images,
      audios: media.audios,
      tiktoks: media.tiktoks,
      counts: {
        likes: safeNumber(topic.votes, 0),
        comments: Math.max(0, safeNumber(topic.postcount, 1) - 1)
      }
    };
    setCached(key, item, CONFIG.publicItemTtl);
  }
  const counts = await getCounts(item);
  const viewer = await getViewer(uid, item);
  return { ...item, counts, viewer };
}
async function getCounts(item) {
  if (!item) return { likes: 0, comments: 0 };
  const key = `counts:${item.tid}:${item.pid}`;
  const cached = getCached(key);
  if (cached) return cached;
  let likes = item.counts && item.counts.likes || 0;
  let comments = item.counts && item.counts.comments || 0;
  try {
    const topic = await Topics.getTopicFields(item.tid, ['votes', 'postcount']);
    likes = safeNumber(topic.votes, likes);
    comments = Math.max(0, safeNumber(topic.postcount, comments + 1) - 1);
  } catch (err) {}
  return setCached(key, { likes, comments }, CONFIG.countsTtl);
}
async function getFeed(uid, page, pageSize) {
  await ensureModules();
  page = Math.max(1, safeNumber(page, 1));
  pageSize = Math.max(1, Math.min(CONFIG.maxPageSize, safeNumber(pageSize, CONFIG.pageSize)));
  const start = (page - 1) * pageSize;
  const stop = start + pageSize - 1;
  const cacheKey = `feed:${CONFIG.cid}:${page}:${pageSize}`;
  let tids = getCached(cacheKey);
  if (!tids) {
    tids = await getTids(CONFIG.cid, start, stop);
    setCached(cacheKey, tids, page === 1 ? CONFIG.firstPageTtl : CONFIG.oldPageTtl);
  }
  const items = (await Promise.all(tids.map(tid => buildPublicItem(tid, uid)))).filter(Boolean);
  return { items, page, pageSize, hasMore: tids.length >= pageSize };
}
async function deleteTopicForUser(tid, uid) {
  await ensureModules();
  const item = await buildPublicItem(tid, uid);
  if (!item) {
    const err = new Error('not-found');
    err.statusCode = 404;
    throw err;
  }
  const allowed = await canManageItem(uid, item);
  if (!allowed) {
    const err = new Error('no-permission');
    err.statusCode = 403;
    throw err;
  }
  if (Topics && typeof Topics.delete === 'function') {
    await Topics.delete(tid, uid);
    invalidateFeedCaches();
    return true;
  }
  const err = new Error('delete-not-supported');
  err.statusCode = 500;
  throw err;
}
function formatApi(helpers, status, res, payload) {
  if (helpers && typeof helpers.formatApiResponse === 'function') return helpers.formatApiResponse(status, res, payload);
  res.status(status).json(payload);
}
plugin.clearCaches = async function clearCaches() {
  invalidateFeedCaches();
};
plugin.init = async function init(params) {
  const router = params.router;
  const middleware = params.middleware;
  if (routeReady) return;
  routeReady = true;
  router.get('/video', middleware.buildHeader, (req, res) => {
    res.render('peipe-video', {
      cid: CONFIG.cid,
      imageMax: CONFIG.imageMax,
      title: '视频发现',
      breadcrumbs: [{ text: '视频发现' }],
      relative_path: nconf.get('relative_path') || ''
    });
  });
};
plugin.addRoutes = async function addRoutes({ router, helpers }) {
  routeHelpers.setupApiRoute(router, 'get', '/peipe-video/feed', [], async (req, res) => {
    const uid = getReqUid(req);
    const page = safeNumber(req.query.page, 1);
    const pageSize = safeNumber(req.query.pageSize, CONFIG.pageSize);
    const data = await getFeed(uid, page, pageSize);
    formatApi(helpers, 200, res, data);
  });
  routeHelpers.setupApiRoute(router, 'delete', '/peipe-video/topics/:tid', [], async (req, res) => {
    const uid = getReqUid(req);
    if (!uid) return formatApi(helpers, 401, res, { error: 'not-logged-in' });
    const tid = String(req.params.tid || '');
    if (!/^\d+$/.test(tid)) return formatApi(helpers, 400, res, { error: 'invalid-topic-id' });
    try {
      await deleteTopicForUser(tid, uid);
      return formatApi(helpers, 200, res, { ok: true, tid });
    } catch (err) {
      winston.error(`[nodebb-plugin-peipe-video] delete topic failed: ${err.stack || err.message}`);
      return formatApi(helpers, err.statusCode || 500, res, { error: err.message || 'delete-failed' });
    }
  });
  routeHelpers.setupApiRoute(router, 'post', '/peipe-video/cache/purge', [], async (req, res) => {
    const uid = getReqUid(req);
    let allowed = false;
    try { allowed = uid && User && typeof User.isAdministrator === 'function' && await User.isAdministrator(uid); } catch (err) {}
    if (!allowed) return formatApi(helpers, 403, res, { error: 'no-permission' });
    invalidateFeedCaches();
    return formatApi(helpers, 200, res, { ok: true });
  });
};
module.exports = plugin;
